# Generated by Django 5.1.5 on 2025-02-02 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clerk_id', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Parent', 'Parent'), ('Child', 'Child')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('points', models.PositiveIntegerField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parentprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='child_profile', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_name', models.CharField(max_length=30)),
                ('quest_description', models.TextField()),
                ('points', models.PositiveIntegerField()),
                ('children', models.ManyToManyField(related_name='quests', to='api.childprofile')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parentprofile')),
            ],
            options={
                'ordering': ['quest_name'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_name', models.CharField(max_length=30)),
                ('reward_description', models.TextField()),
                ('points', models.PositiveIntegerField()),
                ('children', models.ManyToManyField(related_name='rewards', to='api.childprofile')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parentprofile')),
            ],
            options={
                'ordering': ['reward_name'],
            },
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to='api.user'),
        ),
    ]
